Predict Loan status

In [11]:
# pip install imblearn

In [12]:
# rus =  imblearn.under_sampling.RandomUnderSampler()

In [13]:
# smote_os = imblearn.over,SMOTE()

In [14]:
# smote_os.fit_resample(x,y)

In [15]:
# X_os.shape, Y_os.shape

In [16]:
import imblearn
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error
import pickle
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

In [17]:
# x= df[['Current Loan Amount', 'Term']]
# y = df['Loan Status']
# x.shape, y.shape

In [18]:
# X_res, Y_res = rus.fit_resample(x,y)

In [19]:
# X_res.shape, Y_res.shape

In [20]:
train=pd.read_csv("LoansTrainingSet (2).csv")
train

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,000025bb-5694-4cff-b17d-192b1a98ba44,5ebc8bb1-5eb9-4404-b11b-a6eebc401a19,Fully Paid,11520,Short Term,741.0,10+ years,Home Mortgage,33694.0,Debt Consolidation,$584.03,12.3,41.0,10,0,6760,16056,0.0,0.0
1,00002c49-3a29-4bd4-8f67-c8f8fbc1048c,927b388d-2e01-423f-a8dc-f7e42d668f46,Fully Paid,3441,Short Term,734.0,4 years,Home Mortgage,42269.0,other,"$1,106.04",26.3,NaN,17,0,6262,19149,0.0,0.0
2,00002d89-27f3-409b-aa76-90834f359a65,defce609-c631-447d-aad6-1270615e89c4,Fully Paid,21029,Short Term,747.0,10+ years,Home Mortgage,90126.0,Debt Consolidation,"$1,321.85",28.8,NaN,5,0,20967,28335,0.0,0.0
3,00005222-b4d8-45a4-ad8c-186057e24233,070bcecb-aae7-4485-a26a-e0403e7bb6c5,Fully Paid,18743,Short Term,747.0,10+ years,Own Home,38072.0,Debt Consolidation,$751.92,26.2,NaN,9,0,22529,43915,0.0,0.0
4,0000757f-a121-41ed-b17b-162e76647c1f,dde79588-12f0-4811-bab0-e2b07f633fcd,Fully Paid,11731,Short Term,746.0,4 years,Rent,50025.0,Debt Consolidation,$355.18,11.5,NaN,12,0,17391,37081,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256979,fffef5b7-be99-4666-ac70-2a397d2ee435,7211a8e3-cba4-4132-b939-222eed8a662c,Fully Paid,3911,Short Term,NaN,2 years,Rent,NaN,Debt Consolidation,"$1,706.58",19.9,NaN,16,0,43992,44080,0.0,0.0
256980,ffffca93-aa8c-4123-b8ff-7852f6df889a,616fef0c-8f09-4327-9b5c-48fcfaa52934,Fully Paid,5078,Short Term,737.0,10+ years,Own Home,77186.0,Debt Consolidation,"$1,376.47",19.1,47.0,9,0,1717,9758,0.0,0.0
256981,ffffcb2e-e48e-4d2c-a0d6-ed6bce5bfdbe,971a6682-183b-4a52-8bce-1d3429ade295,Charged Off,12116,Short Term,7460.0,9 years,Home Mortgage,52504.0,Debt Consolidation,$297.96,15.1,82.0,8,0,3315,20090,0.0,0.0
256982,ffffcb2e-e48e-4d2c-a0d6-ed6bce5bfdbe,971a6682-183b-4a52-8bce-1d3429ade295,Charged Off,12116,Short Term,746.0,9 years,Home Mortgage,52504.0,Debt Consolidation,$297.96,15.1,82.0,8,0,3315,20090,0.0,0.0
256983,ffffe32e-ed17-459f-9cfd-7b9ee7972933,97281336-1e45-41d2-acb2-263ce56a590e,Fully Paid,27902,Long Term,678.0,10+ years,Home Mortgage,117480.0,Debt Consolidation,"$2,525.82",18.0,11.0,10,0,28317,62371,0.0,0.0

In [21]:
X=train

In [22]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256984 entries, 0 to 256983
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Loan ID                       256984 non-null  object
 1   Customer ID                   256984 non-null  object
 2   Loan Status                   256984 non-null  object
 3   Current Loan Amount           256984 non-null  int64
 4   Term                          256984 non-null  object
 5   Credit Score                  195308 non-null  float64
 6   Years in current job          245508 non-null  object
 7   Home Ownership                256984 non-null  object
 8   Annual Income                 195308 non-null  float64
 9   Purpose                       256984 non-null  object
 10  Monthly Debt                  256984 non-null  object
 11  Years of Credit History       256984 non-null  float64
 12  Months since last delinquent  116601 non-null  float64
 13  Number of Open Accounts       256984 non-null  int64
 14  Number of Credit Problems     256984 non-null  int64
 15  Current Credit Balance        256984 non-null  int64
 16  Maximum Open Credit           256984 non-null  object
 17  Bankruptcies                  256455 non-null  float64
 18  Tax Liens                     256961 non-null  float64
dtypes: float64(6), int64(4), object(9)
memory usage: 37.3+ MB

In [23]:
train.describe()

,Current Loan Amount,Credit Score,Annual Income,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Bankruptcies,Tax Liens
count,2.569840e+05,195308.000000,1.953080e+05,256984.000000,116601.000000,256984.000000,256984.000000,2.569840e+05,256455.000000,256961.000000
mean,1.371331e+07,1251.116099,7.195272e+04,18.290195,34.881450,11.106267,0.156628,1.540656e+04,0.110316,0.027203
std,3.438131e+07,1762.016848,5.887757e+04,7.075747,21.854165,4.982982,0.460731,1.966506e+04,0.336229,0.245950
min,5.050000e+02,585.000000,0.000000e+00,3.400000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,8.299000e+03,714.000000,4.432100e+04,13.500000,16.000000,8.000000,0.000000,5.974000e+03,0.000000,0.000000
50%,1.429800e+04,733.000000,6.124200e+04,17.000000,32.000000,10.000000,0.000000,1.107800e+04,0.000000,0.000000
75%,2.436700e+04,744.000000,8.646200e+04,21.700000,51.000000,14.000000,0.000000,1.931900e+04,0.000000,0.000000
max,1.000000e+08,7510.000000,8.713547e+06,70.500000,176.000000,76.000000,11.000000,1.731412e+06,7.000000,11.000000

In [24]:
train["Monthly Debt"]=train["Monthly Debt"].str.replace("$","")

/var/folders/6f/qftvzclj2fv91pxvhcwx_14m0000gp/T/ipykernel_99141/1118652110.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  train["Monthly Debt"]=train["Monthly Debt"].str.replace("$","")

In [25]:
train["Years in current job"]=train["Years in current job"].str.replace("years","")

In [26]:
train["Years in current job"]=train["Years in current job"].str.replace("+","")

/var/folders/6f/qftvzclj2fv91pxvhcwx_14m0000gp/T/ipykernel_99141/2665355013.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  train["Years in current job"]=train["Years in current job"].str.replace("+","")

In [27]:
train["Monthly Debt"]=train["Monthly Debt"].str.replace(",","")
train

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,000025bb-5694-4cff-b17d-192b1a98ba44,5ebc8bb1-5eb9-4404-b11b-a6eebc401a19,Fully Paid,11520,Short Term,741.0,10,Home Mortgage,33694.0,Debt Consolidation,584.03,12.3,41.0,10,0,6760,16056,0.0,0.0
1,00002c49-3a29-4bd4-8f67-c8f8fbc1048c,927b388d-2e01-423f-a8dc-f7e42d668f46,Fully Paid,3441,Short Term,734.0,4,Home Mortgage,42269.0,other,1106.04,26.3,NaN,17,0,6262,19149,0.0,0.0
2,00002d89-27f3-409b-aa76-90834f359a65,defce609-c631-447d-aad6-1270615e89c4,Fully Paid,21029,Short Term,747.0,10,Home Mortgage,90126.0,Debt Consolidation,1321.85,28.8,NaN,5,0,20967,28335,0.0,0.0
3,00005222-b4d8-45a4-ad8c-186057e24233,070bcecb-aae7-4485-a26a-e0403e7bb6c5,Fully Paid,18743,Short Term,747.0,10,Own Home,38072.0,Debt Consolidation,751.92,26.2,NaN,9,0,22529,43915,0.0,0.0
4,0000757f-a121-41ed-b17b-162e76647c1f,dde79588-12f0-4811-bab0-e2b07f633fcd,Fully Paid,11731,Short Term,746.0,4,Rent,50025.0,Debt Consolidation,355.18,11.5,NaN,12,0,17391,37081,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256979,fffef5b7-be99-4666-ac70-2a397d2ee435,7211a8e3-cba4-4132-b939-222eed8a662c,Fully Paid,3911,Short Term,NaN,2,Rent,NaN,Debt Consolidation,1706.58,19.9,NaN,16,0,43992,44080,0.0,0.0
256980,ffffca93-aa8c-4123-b8ff-7852f6df889a,616fef0c-8f09-4327-9b5c-48fcfaa52934,Fully Paid,5078,Short Term,737.0,10,Own Home,77186.0,Debt Consolidation,1376.47,19.1,47.0,9,0,1717,9758,0.0,0.0
256981,ffffcb2e-e48e-4d2c-a0d6-ed6bce5bfdbe,971a6682-183b-4a52-8bce-1d3429ade295,Charged Off,12116,Short Term,7460.0,9,Home Mortgage,52504.0,Debt Consolidation,297.96,15.1,82.0,8,0,3315,20090,0.0,0.0
256982,ffffcb2e-e48e-4d2c-a0d6-ed6bce5bfdbe,971a6682-183b-4a52-8bce-1d3429ade295,Charged Off,12116,Short Term,746.0,9,Home Mortgage,52504.0,Debt Consolidation,297.96,15.1,82.0,8,0,3315,20090,0.0,0.0
256983,ffffe32e-ed17-459f-9cfd-7b9ee7972933,97281336-1e45-41d2-acb2-263ce56a590e,Fully Paid,27902,Long Term,678.0,10,Home Mortgage,117480.0,Debt Consolidation,2525.82,18.0,11.0,10,0,28317,62371,0.0,0.0

In [28]:
X["Months since last delinquent"].fillna(500, inplace=True)

In [29]:
X[X.duplicated(subset="Loan ID")]

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
7,0000afa6-8902-4f8f-b870-25a8fdad0aeb,e49c1a82-a0f7-45e8-9f46-2f75c43f9fbc,Charged Off,24613,Long Term,NaN,6,Rent,NaN,Business Loan,542.29,17.6,73.0,7,0,14123,16954,0.0,0.0
13,00029f9f-0cc5-4d4e-aabc-ea4a7fe74e12,afbc2fa3-3bad-4d48-b691-829aed78bad5,Charged Off,17961,Short Term,701.0,< 1 year,Own Home,53053.0,Debt Consolidation,596.85,9.9,43.0,7,0,6810,22775,0.0,0.0
14,00029f9f-0cc5-4d4e-aabc-ea4a7fe74e12,afbc2fa3-3bad-4d48-b691-829aed78bad5,Charged Off,17961,Short Term,701.0,< 1 year,Own Home,53053.0,Debt Consolidation,596.85,9.9,43.0,7,0,6810,22775,0.0,0.0
15,00029f9f-0cc5-4d4e-aabc-ea4a7fe74e12,afbc2fa3-3bad-4d48-b691-829aed78bad5,Charged Off,17980,Short Term,701.0,< 1 year,Own Home,53112.0,Debt Consolidation,597.50,9.9,43.0,7,0,6817,22800,0.0,0.0
19,00035328-2636-4390-8322-5841de482d2b,28eb75ac-6a09-4057-b73f-726c72ebf933,Charged Off,11604,Short Term,729.0,6,Home Mortgage,35315.0,Debt Consolidation,662.16,15.0,500.0,12,0,17092,20743,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256972,fffd5218-faf0-4b82-becf-11664fa064a3,301954fb-2381-4d68-a3b0-478870cd49f3,Charged Off,5968,Short Term,746.0,8,Own Home,79568.0,Debt Consolidation,1412.33,22.1,63.0,10,1,4237,0,0.0,0.0
256974,fffe36ec-97a6-460a-a236-640b7e0669f0,6520de3e-5961-47b1-bced-6a8132acb5cc,Charged Off,10575,Long Term,722.0,< 1 year,Rent,30854.0,Debt Consolidation,707.08,14.8,500.0,18,0,20183,23496,0.0,0.0
256976,fffe5140-8725-4fd1-b3bf-9e59cb7834eb,df856c29-ce44-4df7-94a6-bd758a1c1332,Charged Off,34710,Short Term,700.0,9,Rent,148755.0,Business Loan,47.11,34.0,1.0,3,0,2590,37004,0.0,0.0
256978,fffe84cf-67a1-468d-ab7b-cf06a9c4ee14,460c6cf5-4d12-4e3c-a3d0-46dd67c78cce,Charged Off,11953,Short Term,717.0,10,Home Mortgage,39844.0,Debt Consolidation,982.82,11.7,500.0,9,1,4176,4783,1.0,0.0
256982,ffffcb2e-e48e-4d2c-a0d6-ed6bce5bfdbe,971a6682-183b-4a52-8bce-1d3429ade295,Charged Off,12116,Short Term,746.0,9,Home Mortgage,52504.0,Debt Consolidation,297.96,15.1,82.0,8,0,3315,20090,0.0,0.0

In [30]:
X["Loan ID"].value_counts()

3f6bd37a-b0bc-4d85-93c7-eea53df601fb    4
65b03871-1531-46ed-b805-a5df41477f03    4
744f26f5-685b-4c1d-89cc-8f32fef69373    4
7902a3ce-5054-4192-bf2f-bb597f3f870c    4
71121052-b403-4ec8-b3fc-25bb3223ed0d    4
                                       ..
5e122f17-d56f-4785-9912-a1a717b180e1    1
5e127563-cd0b-408c-9fc2-8066c4a3e965    1
5e12efa6-0bec-4b0d-bcea-454fa1ebc9f4    1
5e12f797-9600-4f00-965f-b76be5108331    1
ffffe32e-ed17-459f-9cfd-7b9ee7972933    1
Name: Loan ID, Length: 215700, dtype: int64

In [31]:
X[X["Loan ID"]=="744f26f5-685b-4c1d-89cc-8f32fef69373"]

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
117035,744f26f5-685b-4c1d-89cc-8f32fef69373,0d1af0aa-9442-48ee-aa88-19bc3b5f2513,Charged Off,25128,Short Term,7330.0,10,Own Home,150765.0,Debt Consolidation,3304.27,32.5,500.0,16,0,53590,76667,0.0,0.0
117036,744f26f5-685b-4c1d-89cc-8f32fef69373,0d1af0aa-9442-48ee-aa88-19bc3b5f2513,Charged Off,25255,Short Term,7330.0,10,Own Home,151530.0,Debt Consolidation,3321.03,32.5,500.0,16,0,53862,77056,0.0,0.0
117037,744f26f5-685b-4c1d-89cc-8f32fef69373,0d1af0aa-9442-48ee-aa88-19bc3b5f2513,Charged Off,25255,Short Term,NaN,10,Own Home,NaN,Debt Consolidation,3321.03,32.5,500.0,16,0,53862,77056,0.0,0.0
117038,744f26f5-685b-4c1d-89cc-8f32fef69373,0d1af0aa-9442-48ee-aa88-19bc3b5f2513,Charged Off,25128,Short Term,733.0,10,Own Home,150765.0,Debt Consolidation,3304.27,32.5,500.0,16,0,53590,76667,0.0,0.0

In [32]:
X2=X.drop_duplicates(subset="Loan ID", keep='last')
X2

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,000025bb-5694-4cff-b17d-192b1a98ba44,5ebc8bb1-5eb9-4404-b11b-a6eebc401a19,Fully Paid,11520,Short Term,741.0,10,Home Mortgage,33694.0,Debt Consolidation,584.03,12.3,41.0,10,0,6760,16056,0.0,0.0
1,00002c49-3a29-4bd4-8f67-c8f8fbc1048c,927b388d-2e01-423f-a8dc-f7e42d668f46,Fully Paid,3441,Short Term,734.0,4,Home Mortgage,42269.0,other,1106.04,26.3,500.0,17,0,6262,19149,0.0,0.0
2,00002d89-27f3-409b-aa76-90834f359a65,defce609-c631-447d-aad6-1270615e89c4,Fully Paid,21029,Short Term,747.0,10,Home Mortgage,90126.0,Debt Consolidation,1321.85,28.8,500.0,5,0,20967,28335,0.0,0.0
3,00005222-b4d8-45a4-ad8c-186057e24233,070bcecb-aae7-4485-a26a-e0403e7bb6c5,Fully Paid,18743,Short Term,747.0,10,Own Home,38072.0,Debt Consolidation,751.92,26.2,500.0,9,0,22529,43915,0.0,0.0
4,0000757f-a121-41ed-b17b-162e76647c1f,dde79588-12f0-4811-bab0-e2b07f633fcd,Fully Paid,11731,Short Term,746.0,4,Rent,50025.0,Debt Consolidation,355.18,11.5,500.0,12,0,17391,37081,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256978,fffe84cf-67a1-468d-ab7b-cf06a9c4ee14,460c6cf5-4d12-4e3c-a3d0-46dd67c78cce,Charged Off,11953,Short Term,717.0,10,Home Mortgage,39844.0,Debt Consolidation,982.82,11.7,500.0,9,1,4176,4783,1.0,0.0
256979,fffef5b7-be99-4666-ac70-2a397d2ee435,7211a8e3-cba4-4132-b939-222eed8a662c,Fully Paid,3911,Short Term,NaN,2,Rent,NaN,Debt Consolidation,1706.58,19.9,500.0,16,0,43992,44080,0.0,0.0
256980,ffffca93-aa8c-4123-b8ff-7852f6df889a,616fef0c-8f09-4327-9b5c-48fcfaa52934,Fully Paid,5078,Short Term,737.0,10,Own Home,77186.0,Debt Consolidation,1376.47,19.1,47.0,9,0,1717,9758,0.0,0.0
256982,ffffcb2e-e48e-4d2c-a0d6-ed6bce5bfdbe,971a6682-183b-4a52-8bce-1d3429ade295,Charged Off,12116,Short Term,746.0,9,Home Mortgage,52504.0,Debt Consolidation,297.96,15.1,82.0,8,0,3315,20090,0.0,0.0
256983,ffffe32e-ed17-459f-9cfd-7b9ee7972933,97281336-1e45-41d2-acb2-263ce56a590e,Fully Paid,27902,Long Term,678.0,10,Home Mortgage,117480.0,Debt Consolidation,2525.82,18.0,11.0,10,0,28317,62371,0.0,0.0

In [33]:
X['Home Ownership'].value_counts()

Home Mortgage    124477
Rent             109010
Own Home          22923
HaveMortgage        574
Name: Home Ownership, dtype: int64

In [34]:
X.describe()

,Current Loan Amount,Credit Score,Annual Income,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Bankruptcies,Tax Liens
count,2.569840e+05,195308.000000,1.953080e+05,256984.000000,256984.000000,256984.000000,256984.000000,2.569840e+05,256455.000000,256961.000000
mean,1.371331e+07,1251.116099,7.195272e+04,18.290195,288.962395,11.106267,0.156628,1.540656e+04,0.110316,0.027203
std,3.438131e+07,1762.016848,5.887757e+04,7.075747,232.029189,4.982982,0.460731,1.966506e+04,0.336229,0.245950
min,5.050000e+02,585.000000,0.000000e+00,3.400000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,8.299000e+03,714.000000,4.432100e+04,13.500000,35.000000,8.000000,0.000000,5.974000e+03,0.000000,0.000000
50%,1.429800e+04,733.000000,6.124200e+04,17.000000,500.000000,10.000000,0.000000,1.107800e+04,0.000000,0.000000
75%,2.436700e+04,744.000000,8.646200e+04,21.700000,500.000000,14.000000,0.000000,1.931900e+04,0.000000,0.000000
max,1.000000e+08,7510.000000,8.713547e+06,70.500000,500.000000,76.000000,11.000000,1.731412e+06,7.000000,11.000000

In [55]:
X2['Credit Score'].isnull().sum().sum()

48294

In [56]:
X2["Credit Score"].fillna(X2['Credit Score'].mode()[0], inplace=True)

/Users/hannahgraham/Library/Python/3.8/lib/python/site-packages/pandas/core/generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [57]:
X2['Credit Score'] = X2['Credit Score'].map(lambda x: x/10 if x>801 else x)

/var/folders/6f/qftvzclj2fv91pxvhcwx_14m0000gp/T/ipykernel_99141/1388537812.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X2['Credit Score'] = X2['Credit Score'].map(lambda x: x/10 if x>801 else x)

In [58]:
X2["Home Ownership"]=X2["Home Ownership"].str.replace("HaveMortgage","Home Mortgage")

/var/folders/6f/qftvzclj2fv91pxvhcwx_14m0000gp/T/ipykernel_99141/3805433602.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X2["Home Ownership"]=X2["Home Ownership"].str.replace("HaveMortgage","Home Mortgage")

In [59]:
X2=X2[X2['Current Loan Amount']<99999999]

In [60]:
X2.shape

(180490, 19)

In [ ]:
rename columns to features. Loans = loans.rename(columns={'Loan ID': 'Loan_ID'})

In [ ]:
built heat map to see correlations